# Generated by Django 4.0.4 on 2022-05-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_alter_plantobject_plant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='status',
            field=models.CharField(blank=True, choices=[('Выгрузился', 'Выгрузился'), ('Возврат', 'Возврат')], max_length=15, verbose_name='Статус'),
        ),
    ]
